// Code generated by thriftrw v1.2.0
// @generated

package kv

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.2.0", "go.uber.org/yarpc/internal/examples/thrift-keyvalue/keyvalue/kv")
}
