// Code generated by thriftrw-plugin-yarpc
// @generated

package keyvalueclient

import (
	"context"
	"go.uber.org/thriftrw/wire"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/internal/examples/thrift-keyvalue/keyvalue/kv"
	"go.uber.org/yarpc/encoding/thrift"
	"go.uber.org/yarpc"
)

// Interface is a client for the KeyValue service.
type Interface interface {
	GetValue(
		ctx context.Context,
		Key *string,
		opts ...yarpc.CallOption,
	) (string, error)

	SetValue(
		ctx context.Context,
		Key *string,
		Value *string,
		opts ...yarpc.CallOption,
	) error
}

// New builds a new client for the KeyValue service.
//
// 	client := keyvalueclient.New(dispatcher.ClientConfig("keyvalue"))
func New(c transport.ClientConfig, opts ...thrift.ClientOption) Interface {
	return client{
		c: thrift.New(thrift.Config{
			Service:      "KeyValue",
			ClientConfig: c,
		}, opts...),
	}
}

func init() {
	yarpc.RegisterClientBuilder(func(c transport.ClientConfig) Interface {
		return New(c)
	})
}

type client struct {
	c thrift.Client
}

func (c client) GetValue(
	ctx context.Context,
	_Key *string,
	opts ...yarpc.CallOption,
) (success string, err error) {

	args := kv.KeyValue_GetValue_Helper.Args(_Key)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result kv.KeyValue_GetValue_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	success, err = kv.KeyValue_GetValue_Helper.UnwrapResponse(&result)
	return
}

func (c client) SetValue(
	ctx context.Context,
	_Key *string,
	_Value *string,
	opts ...yarpc.CallOption,
) (err error) {

	args := kv.KeyValue_SetValue_Helper.Args(_Key, _Value)

	var body wire.Value
	body, err = c.c.Call(ctx, args, opts...)
	if err != nil {
		return
	}

	var result kv.KeyValue_SetValue_Result
	if err = result.FromWire(body); err != nil {
		return
	}

	err = kv.KeyValue_SetValue_Helper.UnwrapResponse(&result)
	return
}
